/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventsscheduler;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Ashiqul hoque chowdh
 */
public class ShowEventsFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShowEventsFrame
     */
static int x=0;
    public ShowEventsFrame() {
        initComponents();
        x++;
        populateJTableOnFormLoad(); 
        this.addWindowListener(new WindowAdapter() {

            @Override
            public void windowClosing(WindowEvent e) {
                Exit();
            }
            

            
        });
        //x--;
        
    }
    void Exit()
    {
        int a=JOptionPane.showConfirmDialog(null, "Do you want to close this window? ", "Message", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION)
                {
            this.dispose();
            x--;
                }
        //x--;
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EventsInfoTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        EventsInfoTable.setBackground(new java.awt.Color(232, 248, 245));
        EventsInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EventsId", "EventsName", "Date", "Time", "Description"
            }
        ));
        jScrollPane1.setViewportView(EventsInfoTable);

        jButton1.setBackground(new java.awt.Color(171, 235, 198));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(241, 148, 138));
        Exit.setText("Exit System");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Exit))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateJTableOnFormLoad();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
            UIManager UI2=new UIManager();
            UI2.put("OptionPane.background",new ColorUIResource( 244, 19, 33 ));
            UI2.put("Panel.background",new ColorUIResource( 244, 19, 33 ));
            
         int confirmation=JOptionPane.showConfirmDialog(null,"Do you really want to exit system","Exit",JOptionPane.YES_NO_OPTION);
        if(confirmation==0){
            System.exit(0);
            
        }
    }//GEN-LAST:event_ExitActionPerformed
    private void populateJTableOnFormLoad(){
        // TODO add your handling code here:
 
        DefaultTableModel tableModel = (DefaultTableModel) EventsInfoTable.getModel();
        tableModel.setRowCount(0); //start inserting from first row
        tableModel.setColumnCount(5); //set column number
        EventsInfoTable.setGridColor(Color.black);
        //EventsInfoTable.setForeground(Color.red);
        //EventsInfoTable.setBackground(Color.lightGray);
        //setting column headers
        EventsInfoTable.getColumnModel().getColumn(0).setHeaderValue("EventsId");
        EventsInfoTable.getColumnModel().getColumn(1).setHeaderValue("EventsName");
        EventsInfoTable.getColumnModel().getColumn(2).setHeaderValue("Date");
        EventsInfoTable.getColumnModel().getColumn(3).setHeaderValue("Time");
        EventsInfoTable.getColumnModel().getColumn(4).setHeaderValue("Description");
        EventsInfoTable.getTableHeader().repaint();
        
        try {
            DbConnection dbc = new DbConnection();
            ResultSet rs = dbc.getResultSet();
               
            while (rs.next()) {
                String id = rs.getString("EventsId");
                String name = rs.getString("EventsName");
                String date = rs.getString("Date");
                String time = rs.getString("Time");
                String desc = rs.getString("Description");
                
                System.out.println("\nEvents Id: " + id + "\n"
                        + "Events Name: " + name + "\n"
                        + "Date: " + date+ "\n"
                        + "time: " + time+"\n"
                        + "description: "+desc);
                tableModel.addRow(new Object[]{id, name,date,time,desc});
            }
        } catch (Exception e) {
            System.out.println("Error: " + e);
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowEventsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowEventsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowEventsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowEventsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowEventsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable EventsInfoTable;
    private javax.swing.JButton Exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
